# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fadc35218dcba4df0a2c829ff1fd3e8e50af40edfc965e5a5d839bd2b50a2e2461f2a842508be18357bff9db69756462d83371a1543ea835df9b655f7320ee2

test:
  secret_key_base: f8621f5b3cd13dc8050d510e2d3ad255b98d56e1c422f465a4241b86d30508eaa9a737c7e34c69ca069589b62d6b2f76b8f2711b6f79b87439d455d907703524

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
